FROM node:20-bookworm

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json tsconfig.base.json ./
COPY packages ./packages
COPY apps/worker ./apps/worker

RUN pnpm -C /app install --frozen-lockfile=false
RUN pnpm -C /app/apps/worker build

CMD ["node","/app/apps/worker/dist/index.js"]
