name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "9"

jobs:
  validate:
    name: Validate (lint / typecheck / unit)
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify workspace integrity
        run: |
          node --version
          pnpm --version
          pnpm -r --parallel --if-present run --help >/dev/null || true
          pnpm -r --parallel --if-present run lint --help >/dev/null || true

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Unit tests
        run: pnpm test:unit

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-artifacts
          path: |
            **/coverage/**
            **/test-results/**
            **/junit.xml
          if-no-files-found: ignore

  build:
    name: Build (monorepo)
    runs-on: ubuntu-latest
    timeout-minutes: 35
    needs: [ validate ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            apps/**/.next/**
            apps/**/dist/**
            packages/**/dist/**
          if-no-files-found: ignore
