name: E2E

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "9"

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 55

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: gitnut
          POSTGRES_PASSWORD: gitnut
          POSTGRES_DB: gitnut
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd "pg_isready -U gitnut"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 12

      redis:
        image: redis:7
        ports: [ "6379:6379" ]
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 12

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all packages/apps
        run: pnpm build

      - name: Run migrations
        env:
          DATABASE_URL: postgresql://gitnut:gitnut@localhost:5432/gitnut
        run: pnpm --filter @gitnut/api prisma:migrate:deploy

      - name: Start API (background)
        env:
          DATABASE_URL: postgresql://gitnut:gitnut@localhost:5432/gitnut
          REDIS_URL: redis://localhost:6379
          SESSION_SECRET: test-secret
          PUBLIC_BASE_URL: http://localhost:3001
          PORT: "3001"
        run: |
          nohup pnpm --filter @gitnut/api start > /tmp/api.log 2>&1 &
          sleep 3

      - name: Start Worker (background)
        env:
          DATABASE_URL: postgresql://gitnut:gitnut@localhost:5432/gitnut
          REDIS_URL: redis://localhost:6379
          GITNUT_STORAGE_DRIVER: local
          GITNUT_STORAGE_LOCAL_DIR: /tmp/gitnut-storage
        run: |
          nohup pnpm --filter @gitnut/worker start > /tmp/worker.log 2>&1 &
          sleep 3

      - name: Start Web (background)
        env:
          NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
          PORT: "3000"
        run: |
          nohup pnpm --filter @gitnut/web start > /tmp/web.log 2>&1 &
          sleep 3

      - name: Run Playwright tests
        env:
          BASE_URL: http://localhost:3000
        run: pnpm --filter @gitnut/web test:e2e

      - name: Upload reports and logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-artifacts
          path: |
            /tmp/api.log
            /tmp/worker.log
            /tmp/web.log
            apps/web/playwright-report/**
            apps/web/test-results/**
          if-no-files-found: ignore
