name: SDK

on:
  push:
    branches: [ main ]
    paths:
      - "packages/sdk/**"
      - "packages/shared/**"
      - "programs/**/idl/**"
      - ".github/workflows/sdk-ci.yml"
  pull_request:
    paths:
      - "packages/sdk/**"
      - "packages/shared/**"
      - "programs/**/idl/**"
      - ".github/workflows/sdk-ci.yml"
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "9"

jobs:
  sdk:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared + sdk
        run: pnpm --filter @gitnut/shared... --filter @gitnut/sdk... build

      - name: Test SDK
        run: pnpm --filter @gitnut/sdk test

      - name: Package (dry run)
        run: |
          mkdir -p /tmp/sdk-pack
          pnpm --filter @gitnut/sdk pack --pack-destination /tmp/sdk-pack

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: sdk-package
          path: /tmp/sdk-pack/*.tgz
          if-no-files-found: error
