name: Web

on:
  push:
    branches: [ main ]
    paths:
      - "apps/web/**"
      - "packages/ui/**"
      - "packages/shared/**"
      - ".github/workflows/web-ci.yml"
  pull_request:
    paths:
      - "apps/web/**"
      - "packages/ui/**"
      - "packages/shared/**"
      - ".github/workflows/web-ci.yml"
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_VERSION: "20"
  PNPM_VERSION: "9"

jobs:
  web:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          NEXT_PUBLIC_CHAIN: devnet
          NEXT_PUBLIC_RPC_URL: https://api.devnet.solana.com
          NEXT_PUBLIC_API_BASE_URL: http://localhost:3001
        run: pnpm --filter @gitnut/web build

      - name: Test
        run: pnpm --filter @gitnut/web test

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-artifacts
          path: |
            apps/web/.next/**
            apps/web/test-results/**
            apps/web/coverage/**
          if-no-files-found: ignore
